### ISSUE TITLE
SavingAccount. При оплате через метод pay баланс нарушает граничное значение minBalance.

### ISSUE THREAD

**Issue by Paspy95** [KorzunE/JavaDiplom#10]
# Описание
При использовании метода `pay` итоговый баланс падает ниже минимального баланса.

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе SavingAccount с положительным значением `initialBalance` ( 2_000 ) и минимальным балансом (1_000 )
2. Добавить метод `pay` на сумму 1_500
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит, ожидаемая сумма в 2_000 совпадает с фактической.
_Фактический результат:_ На консоли выводится ошибка, фактическая сумма 500, что меньше минимального баланса.

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/146121803/eef98cdc-d9c1-4bb3-a755-ce63466adfa6)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L78-L90
# Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by KorzunE** [comment]
Дефект исправлен!
