### ISSUE TITLE
SavingAccount. Не срабатывает исключение IllegalArgumentException, если минимальный баланс отрицательный.

### ISSUE THREAD

**Issue by Paspy95** [KorzunE/JavaDiplom#11]
# Описание
В требованиях указано, что _"Если параметры некорректны (мин. баланс больше максимального и так далее), то должно выкидываться исключения вида IllegalArgumentException."

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе SavingAccount с отрицательным минимальным балансом.
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит исключение IllegalArgumentException, 
_Фактический результат:_ На консоли выводится Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/146121803/91500ac3-b8e8-469f-9cda-4e77f9bf760d)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L92-L98
# Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by KorzunE** [comment]
Дефект исправлен!
