### ISSUE TITLE
SavingAccount. Не срабатывает исключение IllegalArgumentException, если начальный баланс отрицательный.

### ISSUE THREAD

**Issue by Paspy95** [KorzunE/JavaDiplom#13]
# Описание
В требованиях указано, что _"Если параметры некорректны (мин. баланс больше максимального и так далее), то должно выкидываться исключения вида IllegalArgumentException."_ 

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе SavingAccount с отрицательным начальным балансом.
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит исключение IllegalArgumentException, 
_Фактический результат:_ На консоли выводится Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/146121803/c3d7304d-472f-4be6-91ee-74048fd89502)
# Тест
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L108-L114
# Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by KorzunE** [comment]
Дефект исправлен!
