### ISSUE TITLE
Credit Account. Не выбрасывает исключение IllegalArgumentException, если начальный баланс отрицательный.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#2]
# Описание
В требованиях указано, что _"Если параметры некорректны (кредитный лимит отрицательный и так далее), то должно выкидываться исключения вида IllegalArgumentException."_ 

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/ddf5e3fe3eb09342c478783bafdfe7673ac0a796/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L22
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount с отрицательным начальным балансом.
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит исключение IllegalArgumentException, 
_Фактический результат:_ На консоли выводится Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/cac3a75d-971f-4cdf-a9ec-0f5a99176050)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/ddf5e3fe3eb09342c478783bafdfe7673ac0a796/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L27-L30
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
