### ISSUE TITLE
Credit Account. При пополнении баланса итоговая сумма не учитывает начальный баланс и равняется сумме пополнения.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#3]
# Описание
При пополнении баланса итоговая сумма не учитывает начальный баланс, расчет проводится с ошибкой и финальный баланс равняется сумме пополнения.

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/ddf5e3fe3eb09342c478783bafdfe7673ac0a796/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L64-L71
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount со значением начального баланса 2_000
1. Добавить метод add на 3_000
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Итоговая сумма равняется 5_000.
_Фактический результат:_ Итоговая сумма равняется 3_000.
# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/556f247d-8e17-4ae9-85e3-a85b858189a0)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/6ffc260cf4ddb52b1a1c62a7e0ff4e7d2e24dac3/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L33-L39
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
