### ISSUE TITLE
Credit Account. При оплате через метод pay итоговый баланс рассчитывается неверно.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#4]
# Описание
При использовании метода `pay` итоговый баланс рассчитывается неверно. (_получается отрицательное число_)

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/15b1bae8c6e979a5bc84147dcf87029cb61366da/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L39-L51
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount с положительным значением `initialBalance` (_например 2_000_)
2. Добавить метод `pay` на сумму 1_000
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит, ожидаемая сумма в 1_000 совпадает с фактической.
_Фактический результат:_ На консоли выводится ошибка, фактическая сумма отрицательное число (-1000).

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/c270ff0f-de95-4f78-a228-3b1749e4d7de)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/15b1bae8c6e979a5bc84147dcf87029cb61366da/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L48-L58
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
