### ISSUE TITLE
Credit Account. Производится расчет процентов при положительном балансе.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#5]
# Описание
Производится расчет процентов при положительном балансе хотя в требованиях указано, что _"если на счёте 200 рублей, то при любой ставке ответ должен быть 0."_ 

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/2d8e29eb66040f775aae81006e02ce1732207133/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L84
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount с балансом 2_000
2. Запросить расчет `yearChange`
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Проценты при положительном балансе не начисляются результат : 0 
_Фактический результат:_ Проценты рассчитываются получаем результат 300

# Скриншот

![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/897e0e81-591c-4148-826c-7dc9fc4790dd)
# Тест
https://github.com/KorzunE/JavaDiplom/blob/2d8e29eb66040f775aae81006e02ce1732207133/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L60-L67
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
