### ISSUE TITLE
Credit Account. Производится расчет процентов при нулевом балансе.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#6]
# Описание
Производится расчет процентов при нулевом балансе, что не соответствует логике и условию задания _"если на счёте 200 рублей, то при любой ставке ответ должен быть 0."_ 
# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/2d8e29eb66040f775aae81006e02ce1732207133/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L81-L84
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount с балансом 2_000.
2. Выполнить метод `pay` на сумму равную начальному балансу (2_000)
3. Запросить расчет `yearChange`
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Проценты не рассчитываются результат : 0 
_Фактический результат:_ Проценты рассчитываются, получаем результат -300 (_в соответствии с заданным начальным балансом_)

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/d9a70538-bfd7-4e2b-937c-5b51b8fb2787)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/521d14245d49d25095e6cbfabc207361171119ef/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L75-L84
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
