### ISSUE TITLE
Credit Account. Отрицательный баланс превышает возможный кредитный лимит.

### ISSUE THREAD

**Issue by KorzunE** [KorzunE/JavaDiplom#7]
# Описание
При исполнении метода `pay` возможно получение отрицательного баланса больше чем заданный кредитный лимит, что противоречит условию _" Может иметь баланс вплоть до отрицательного, но до указанного кредитного лимита."_ 
и условию покупки _"Операция оплаты с карты на указанную сумму.
     * В результате успешного вызова этого метода, баланс должен уменьшиться
     * на сумму покупки. Если же операция может привести к некорректному
     * состоянию счёта (например, баланс может уйти меньше чем лимит), то операция должна
     * завершиться вернув false и ничего не поменяв на счёте."_
# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/521d14245d49d25095e6cbfabc207361171119ef/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L39-L51
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе CreditAccount с балансом 2_000.
2. Выполнить метод `pay` на сумму 10_000, превышающую начальный баланс и кредитный лимит.
3. Запросить `getBalance`
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Оплата не проходит, итоговый результат 2_000 (_на счетах ничего не меняется._) 
_Фактический результат:_ Оплата проходит превышая возможный кредитный лимит. Итоговый результат -8_000
# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/145035972/1f6ac2d1-6474-4ba3-9f0d-474e59ecf4a5)
# Тест
https://github.com/KorzunE/JavaDiplom/blob/019924591d9669e37b069ad117539ba3a1d1b5c7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L98-L107
# Окружение
Операционная система: Windows 11
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by Paspy95** [comment]
баг исправлен!
