### ISSUE TITLE
SavingAccount. При пополнении баланса изначальный баланс не учитывается.

### ISSUE THREAD

**Issue by Paspy95** [KorzunE/JavaDiplom#8]
# Описание
При пополнении баланса итоговая сумма не учитывает начальный баланс, расчет проводится с ошибкой и финальный баланс равняется сумме пополнения.

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе SavingAccount со значением начального баланса больше нуля
1. Добавить метод add на валидную сумму больше нуля
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Итоговая сумма равняется(5_000) начальному балансу (2_000) и сумме пополнения(3_000). 
_Фактический результат:_ Итоговая сумма равняется(3_000) только сумме пополнения(3_000).
# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/146121803/f782c730-61a7-48a7-9502-bdf89f617e55)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L20
# Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by KorzunE** [comment]
Баг исправлен!
