### ISSUE TITLE
SavingAccount. При покупке через метод pay баланс рассчитывается неверно.

### ISSUE THREAD

**Issue by Paspy95** [KorzunE/JavaDiplom#9]
# Описание
При использовании метода `pay` получаем отрицательное число.

# Локализация дефекта
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L43-L54
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/KorzunE/JavaDiplom) в IDEA
1. Создать объект в классе SavingAccount с положительным значением `initialBalance` (_например 2_000_)
2. Добавить метод `pay` на сумму 3_000
1. Запустить программу
1. Посмотреть вывод консоли
_Ожидаемый результат:_ Тест проходит, ожидаемая сумма в 2_000 совпадает с фактической.
_Фактический результат:_ На консоли выводится ошибка, фактическая сумма отрицательное число (-1000).

# Скриншот
![image](https://github.com/KorzunE/JavaDiplom/assets/146121803/2d6c6b29-a393-4433-8a37-16ad52bd8e90)

# Тест
https://github.com/KorzunE/JavaDiplom/blob/89f39d5cce9292ee4d15fea795d7dc18a220b2df/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L50-L62
# Окружение
Операционная система: Windows 10
IDE: IntelliJ IDEA 2023.2.2 (Community Edition)
Java: OpenJDK11

**Comment by KorzunE** [comment]
Дефект исправлен!
